- name: Setup Frontend
  hosts: all
  tasks:
    - name: Installing Nginx server
      ansible.builtin.yum:
        name: nginx
        state: latest







#echo -e "${color} Installing Nginx server ${nocolor}"
#eyum install nginx -y &>>/tmp/roboshop.log 
#estat_check $?

#eecho -e "${color} Removing old App content ${nocolor}" 
#erm -rf /usr/share/nginx/html/* &>>/tmp/roboshop.log 
#estat_check $?

#eecho -e "${color} Downloading Fronted content ${nocolor}"
#ecurl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip  &>>/tmp/roboshop.log 
#estat_check $?

#eecho -e "${color} Extract Fronted content ${nocolor}"
#cd /usr/share/nginx/html   
#cd /usr/share/nginx/html   
#unzip /tmp/frontend.zip &>>/tmp/roboshop.log
#stat_check $?

#echo -e "${color} Update Fronted Configuration ${nocolor}"
#cp /home/centos/learn-shell/roboshop-shell/roboshop.conf  /etc/nginx/default.d/roboshop.conf &>>/tmp/roboshop.log
#stat_check $?

#echo -e "${color} Starting Nginx server ${nocolor}"
#systemctl enable nginx &>>/tmp/roboshop.log  
#systemctl restart nginx &>>/tmp/roboshop.log  
#stat_check $?